# config file for transfer learning example on MNIST

training:
  batch_size: 64
  n_epochs: 200
  n_iters: 5001
  ngpu: 1
  snapshot_freq: 1000
  algo: 'dsm'
  anneal_power: 2.0

data:
  dataset: "MNIST"
  image_size: 28
  channels: 1
  logit_transform: false
  random_flip: false
  random_state: 0
  split_size: .15
  on_gpu: true


model:
  sigma_begin: 1
  sigma_end: 0.01
  num_classes: 10
  batch_norm: false
  ngf: 64
  final_layer: true
  feature_size: 200
  num_components: 40
  learn_y_prior: true
  augment: false
  positive: false
  architecture: 'mlp'
  decoder_var: 0.1
  retrain: false

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0005
  beta1: 0.9
  amsgrad: false

