# config file for transfer learning example on CIFAR10

training:
  batch_size: 64
  n_epochs: 200
  n_iters: 5001
  ngpu: 1
  snapshot_freq: 1000
  algo: 'dsm'
  anneal_power: 2.0

data:
 dataset: "SVHN"
 image_size: 32
 channels: 3
 logit_transform: false
 random_flip: false
 random_state: 0
 split_size: .33
 on_gpu: true


model:
  sigma_begin: 1
  sigma_end: 0.01
  num_classes: 10
  batch_norm: false
  ngf: 16
  final_layer: true
  feature_size: 200
  num_components: 100
  learn_y_prior: true
  augment: false
  positive: false
  architecture: 'convmlp'
  decoder_var: 0.01
  retrain: true

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false

